### ISSUE TITLE
LuckPerms

### ISSUE THREAD

**Issue by EmanYm** [FabioZumbi12/Sponge-RankUpper#15]
I'm sure that one permission plugin will work the same as the next, but I have to ask for my own sanity.
Does RankUpper work with LuckPerms out of the box?

**Comment by Wissi** [comment]
Many are having issues due to not knowing how to setup the proper groups to work with this plugin. Dev has stated in the config file that is generated:
```
        # ##################################################################################
        # IMPORTANT: Exact name of group to promote player on match the requiriments.
        # IMPORTANT: Pay attention on group inherits. I (dev of this plugin) cant help you with permissions plugin configuration.
        # The player will be promoted based on command you put on "execute-commands" and with placeholder {newgroup} on commands.
        # ##################################################################################
```
Luckperms has a much more "flexible" (complicated) way to setup groups and they state:
https://github.com/lucko/LuckPerms/wiki/Default-Groups
```
There's also issues with rankup plugins. If you want a "main" group, and then separate "level" ranks, you need to be able to grant more than one group by default.
```
Unless you know very well how Luckperms works and are able to understand/create the proper group(s), it will NOT be an "out of box" experience.

Dev here will not respond to these questions, I've tried to make it work with Permission manager and still no support.
If you have a valid luckperms way of making it work, pls share.

**Comment by EmanYm** [comment]
I'm setting up a (Sponge) server for someone, and they insist on using RankUpper.  They had messed up the config, but I got that fixed.
The server loads with no more errors.  I just don't like the modpack he's chosen, so I have not tested if it works yet.

**Comment by Wissi** [comment]
Rankupper is Working? Or just loaded w/o issues (it does that in almost all cases), problem is verufying that it actually works. that players get ranked up accordingly. U are using luckperms?

**Comment by EmanYm** [comment]
Yes.  Luckperms, spongeforge
I was able to set a 5 minute timer to move myself from default to member successfully.

**Comment by FabioZumbi12** [comment]
Already updated to work with LP, download the latest from ORE.
